# Generated by Django 4.1 on 2022-08-21 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="NFT",
        ),
    ]
