# Generated by Django 4.1 on 2022-08-21 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_nft"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="NFT",
            new_name="Adventure_NFT",
        ),
    ]
